#ifndef MOTORS_H_
#define MOTORS_H_

#include "../../LP_MSPM0G3507/timer.h"
#include "PWM.h"

#define LEFT_MOTOR_PWM_PORT GPIOA
#define LEFT_MOTOR_PWM_PIN 18
#define LEFT_MOTOR_PWM_MASK ((uint32_t)(0x00000001U << LEFT_MOTOR_PWM_PIN))

#define LEFT_MOTOR_AIN1_PORT GPIOA
#define LEFT_MOTOR_AIN1_PIN 24
#define LEFT_MOTOR_AIN1_MASK ((uint32_t)(0x00000001U << LEFT_MOTOR_AIN1_PIN))
#define LEFT_MOTOR_AIN1_INDEX PA24INDEX
#define LEFT_MOTOR_AIN2_PORT GPIOA
#define LEFT_MOTOR_AIN2_PIN 17
#define LEFT_MOTOR_AIN2_MASK ((uint32_t)(0x00000001U << LEFT_MOTOR_AIN2_PIN))
#define LEFT_MOTOR_AIN2_INDEX PA17INDEX

#define RIGHT_MOTOR_PWM_PORT GPIOB
#define RIGHT_MOTOR_PWM_PIN 19
#define RIGHT_MOTOR_PWM_MASK ((uint32_t)(0x00000001U << RIGHT_MOTOR_PWM_PIN))

#define RIGHT_MOTOR_AIN1_PORT GPIOA
#define RIGHT_MOTOR_AIN1_PIN 22
#define RIGHT_MOTOR_AIN1_MASK ((uint32_t)(0x00000001U << RIGHT_MOTOR_AIN1_PIN))
#define RIGHT_MOTOR_AIN1_INDEX PA22INDEX
#define RIGHT_MOTOR_AIN2_PORT GPIOB
#define RIGHT_MOTOR_AIN2_PIN 18
#define RIGHT_MOTOR_AIN2_MASK ((uint32_t)(0x00000001U << RIGHT_MOTOR_AIN2_PIN))
#define RIGHT_MOTOR_AIN2_INDEX PB18INDEX

// Defines for PWM
#define PWM_PERIOD (10 * ONE_MILLISECOND_DELAY)
#define PWM_DELTA (100 * ONE_MICROSECOND_DELAY)
#define PWM_PRESCALE 31
#define RIGHT_PWM_TIMER TIMG8
#define LEFT_PWM_TIMER TIMG7

void initializeMotors();
void driveMotor(GPTIMER_Regs *pwmTimer, Timer_PWMConfig *PWMTimerPWMConfig,
                GPIO_Regs *ain1Port, uint32_t ain1Mask, GPIO_Regs *ain2Port,
                uint32_t ain2Mask, uint8_t vel, int dir);

#endif